In [1]:
import numpy as np


In [3]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = np.random.randint(0,5,3)
a

array([4, 4, 4], dtype=int32)

In [8]:
a = np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
a = [5]*10
a

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

In [23]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a =np.random.rand(9).reshape(3,3)
a

array([[0.02076355, 0.76169597, 0.89248758],
       [0.49839078, 0.76363714, 0.62411687],
       [0.97861286, 0.42155168, 0.29483953]])